//
// Created by martijn on 29-11-21.
//

#ifndef TEST_OBSERVATION_TYPE_H
#define TEST_OBSERVATION_TYPE_H

typedef enum observation_type {
    BODY_TEMPERATURE = 0,
    BLOOD_PRESSURE_SYSTOLIC = 1,
    BLOOD_PRESSURE_DIASTOLIC = 2,
    BLOOD_PRESSURE_MEAN = 3,
    BLOOD_PRESSURE_PULSE = 4,
    BODY_WEIGHT = 5,
    BLOOD_OXYGEN_SATURATION = 6,
    PULSE_OXIMETRY_PULSE = 7,
    BLOOD_GLUCOSE = 8
} ObservationType;

#endif //TEST_OBSERVATION_TYPE_H
